### PR TITLE
Validate contact form

### PR DESCRIPTION
**Pull request by NJ-2020**
Dear Reviewer, 

We create a basic form validation - client-side with the following features:
- email must be in lower case.
- If the validation is ok, the form will be sent, otherwise, the form will not be sent and an error message appears near the submit button.

Please note that we could not find the template for the validation message in Figma, hence we style the validation message in white color.

Thank you.

Novell and Moses

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

mario_ladders

## Good points 👍 
- No Linters error ✔️

## Aspects to improve ♻️

- [ ] Let's think as a user, I type my info and there, I got an error with my e-mail because is invalid, when I saw it, how could I know what's the problem? Maybe a notification like "the e-mail should be lowercase" could help to understand what's the problem with my email.
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, consider:
- [OPTIONAL] All images are not available on the project, I kindly invite you to fix it.
image
- [OPTIONAL] Some background colors are different from the Figma template, I invite you to work on that (contact me section, projects section).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NJ-2020** [comment]
Dear Reviewer, 

I have updated my contact form as per feedback.

Thanks
Novell

**Review by vichuge — APPROVED** [review]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

InbornCandidHornet-size_restricted

## Optional improvements ☑️ 
- It should be great if the lowercase notification would be closer to the submit button (as the beginning)
image

- When I press the submit button, this doesn't change the color according to [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122). I invite you to work on this 😄 
image

- Talking more about design, the border for submit button could improve a little bit, look at the screenshot for [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NJ-2020** [comment]
Thank you very much Victor, you very clear.
Great reviewer indeed.

I will do the rest on the weekend

Regards

**Pull request merged**
